app:
  port: ':3200'
  cert_file: './cmd/api/certificate.pem'
  key_file: './cmd/api/key.pem'
  time_format: '2006-01-02T15:04:05'

es:
  host: '192.168.0.64'
  port: '9200'
  cluster: 'superheromatch'
  index: 'superhero'

health:
  port: ':8240'
  shutdown_endpoint: '/api/v1/superhero_screen_health/shutdown'
  content_type: 'application/json'